// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmqohckqlpkwtpzqimxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtcW9oY2txbHBrd3RwenFpbXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mjc5NjUsImV4cCI6MjA3MjMwMzk2NX0.rmVQ2tFrQQ1f3llsuhxDMGZynxru4UrFWfW-prNgFKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});